services:
  mysql-backup:
    image: latzzo/mysql-backup-runner:latest
    env_file:
      - .env
    networks:
      - network_default
    volumes:
      - ~/.ssh:/root/.ssh/:ro
      - ./logs:/var/log
      - ./backups:/backup
    restart: "no"

networks:
  network_default:
    external: true